[package]
name = "gourami_social"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[dependencies]
activitystreams = "0.5.0"
askama = "0.8.0"
bcrypt = "0.7.0"
cookie = "0.13.3"
chrono = "0.4.11"
diesel = { version = "1.4.4", features = ["sqlite", "r2d2"] }
env_logger = "0.7.1"
lazy_static = "1.4.0"
log = "0.4.8"
rand = "0.7.3"
reqwest = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2.17", features = ["macros"] }
warp = "0.2.2"
hyper = "0.13"
regex = "1.3.6"
ammonia = "3.1.0"
maplit = "1.0.2"

[dev-dependencies]
