[package]
name = "gourami_social"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[dependencies]
askama = "0.8"
diesel = { version = "1.0.0", features = ["sqlite"] }
tokio = { version = "0.2", features = ["macros"] }
log = "0.4"
env_logger = "0.7"
warp = "0.2"
reqwest = "0.10"
activitystreams = "0.4.0"
chrono = "*"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"


[dev-dependencies]
