[package]
name = "gourami_social"
version = "0.1.0"
authors = ["alex wennerberg <alex@alexwennerberg.com>"]
edition = "2018"

[dependencies]
activitystreams = "0.4.0"
askama = "0.8"
bcrypt = "0.7"
cookie = "0.13"
chrono = "*"
diesel = { version = "1.4", features = ["sqlite", "r2d2"] }
env_logger = "0.7"
lazy_static = "1.4.0"
log = "0.4"
rand = "0.7"
reqwest = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
hyper = "0.13"
regex = "1.3"
ammonia = "3"
maplit = "1.0.2"

[dev-dependencies]
