name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron: "00 00 * * 01"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sqlite
      run: sudo apt-get install sqlite3 libsqlite3-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
